# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62465c1584c321e1ea6e940b7107f265ad83f46b887b26e7018176e9e38791b6ccd14da2e49a5d621b17764777555e1f95f940eea6db07837d5c600a07ef54a8

test:
  secret_key_base: dcc065e12dd7b5b4b1744bb65525bf21564dc13faccac3d5f537030425500bbc4525bc2360e9a463c29b2764c4706e4bbf5c361abb869395772a9dabf04057a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
